/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Admin_pageRouteRouteImport } from './routes/admin_page/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Admin_pageIndexRouteImport } from './routes/admin_page/index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'

const Admin_pageRouteRoute = Admin_pageRouteRouteImport.update({
  id: '/admin_page',
  path: '/admin_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_pageIndexRoute = Admin_pageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Admin_pageRouteRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin_page': typeof Admin_pageRouteRouteWithChildren
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin_page/': typeof Admin_pageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin_page': typeof Admin_pageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin_page': typeof Admin_pageRouteRouteWithChildren
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin_page/': typeof Admin_pageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin_page' | '/imoveis/$slug' | '/admin_page/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/imoveis/$slug' | '/admin_page'
  id: '__root__' | '/' | '/admin_page' | '/imoveis/$slug' | '/admin_page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin_pageRouteRoute: typeof Admin_pageRouteRouteWithChildren
  ImoveisSlugRoute: typeof ImoveisSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin_page': {
      id: '/admin_page'
      path: '/admin_page'
      fullPath: '/admin_page'
      preLoaderRoute: typeof Admin_pageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_page/': {
      id: '/admin_page/'
      path: '/'
      fullPath: '/admin_page/'
      preLoaderRoute: typeof Admin_pageIndexRouteImport
      parentRoute: typeof Admin_pageRouteRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Admin_pageRouteRouteChildren {
  Admin_pageIndexRoute: typeof Admin_pageIndexRoute
}

const Admin_pageRouteRouteChildren: Admin_pageRouteRouteChildren = {
  Admin_pageIndexRoute: Admin_pageIndexRoute,
}

const Admin_pageRouteRouteWithChildren = Admin_pageRouteRoute._addFileChildren(
  Admin_pageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin_pageRouteRoute: Admin_pageRouteRouteWithChildren,
  ImoveisSlugRoute: ImoveisSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
